version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'pipenv-{{ checksum "Pipfile.lock"  }}'
      - run:
          command: |
            pip install pipenv
            pipenv sync --dev
          name: Sync pipenv
      - run:
          command: pipenv run pytest
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
